### ISSUE TITLE
CryptoJS.AES  'iv' is not used in my case

### ISSUE THREAD

**Issue by bengivre** [brix/crypto-js#105]
Hi, 
I'm trying to use CryptoJS.AES to encrypt/decrypt text.  With crypto-js and node.js on linux
My problem is that IV does not look to be used . 
I encrypt passing IV , whatever the value of IV to decrypt, decryption works. 

Here is the code to encrypt:
``` 
var iv_length = 16; 
var iv = CryptoJS.lib.WordArray.random(iv_length);
var aes_options = { iv: iv, mode: CryptoJS.mode.CBC, padding: CryptoJS.pad.Pkcs7 };
var aes256_array = CryptoJS.AES.encrypt(pbkdf2_string, master_key_256, aes_options);
var aes256_string = aes256_array.toString();
```

Here is the code to decrypt:
``` 
// Decrypt AES256 BD
var iv_length = 16; 
var iv = salt_iv_array[0];  // This value come from the IV saved in BD during encryption 
var aes_options = { iv: iv, mode: CryptoJS.mode.CBC, padding: CryptoJS.pad.Pkcs7 };
var bytes_bd  = CryptoJS.AES.decrypt(data.device_address, master_key_256, aes_options);
var plaintext_BD = bytes_bd.toString(CryptoJS.enc.Utf8);
``` 

So whatever the value of IV used to encrypt , I can remove IV from decrypt and it works. 
Maybe I'm missing something ? 

Regards,
Benoit

**Comment by bengivre** [comment]
Well, looks like changing a little bit the IV is not having any impact, but changing it fully get an error like 

```
Error: Malformed UTF-8 data
    at Object.C_enc.Utf8.stringify (/root/node_modules/crypto-js/core.js:478:24)
    at Object.C_lib.WordArray.Base.extend.toString (/root/node_modules/crypto-js/core.js:215:38)
    at myCallback (/root/decrypt_mac_sql.js:82:29)
    at Object.<anonymous> (/root/decrypt_mac_sql.js:101:125)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

```
So I guess, IV is now used correctly
