### ISSUE TITLE
I get a error ,I can not resolve it. please help me 

### ISSUE THREAD

**Issue by zhuijing** [brix/crypto-js#249]
## this is my php code, it can work.  i want to use nodejs .
```
function stripPKSC7Padding($source){
	$char = substr($source, -1);
	$num = ord($char);
	if($num==62)return $source;
	$source = substr($source,0,-$num);
	return $source;
}
function decrypt($str,$screct_key){
	$str = base64_decode($str);
	$screct_key = base64_decode($screct_key);
         $iv_size = mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128,MCRYPT_MODE_CBC);
        $iv = str_repeat("\0", $iv_size);
	$decrypt_str = mcrypt_decrypt(MCRYPT_RIJNDAEL_128, $screct_key, $str, MCRYPT_MODE_CBC, $iv);
	$decrypt_str = stripPKSC7Padding($decrypt_str);
	return $decrypt_str;
}
```

## this is nodejs code.

```var CryptoJS = require("crypto-js");
var data = "4m4HcVZR14pvTtmNbqgkH3qtmLhJpCZx6oi6u2stmGUo2Z3OmKhtHF/VaiFQ023pKJvhXwSRVjC3IBaotOduxO/zIrIqfg+xnvBWY2zYC/UDLPbsm66yz8omvQLRBGsP8MHYLaOFEgFUgREOCa8AKH7u9v6YlnTIdp1XZGGZnKydissMwTiU4xrM5quZnFwqgTSXmCzSEfeHfjr4qTO+pLGRfY/0J/U932FCq012udkj0pA1UspfCnUU4LY8z3AiPr63TKS4ZEj5Pxz5x7beTf5pGQDrrFHaB87/dbbo8V/143RalmWsyNTiKlAA6S8OO4uXtL6tkYXCddyYQnk6waYqrZOgJLnVS5o9PLzzChU="
var aes = 'Lj59Ubk1ZyzlUZGTKgTl6A==';
// Base64  Utf8
var response =  CryptoJS.enc.Base64.parse(data).toString();
var aes1 =  CryptoJS.enc.Base64.parse(aes).toString();
var bytes  = CryptoJS.AES.decrypt(response, aes1, {
  iv: '',
  mode: CryptoJS.mode.CBC,
  padding: CryptoJS.pad.Pkcs7
});

var plaintext = bytes.toString(CryptoJS.enc.Utf8);
```

my code can not work.please help me ,thanks.

**Comment by zhuijing** [comment]
**this is my error**

```
/demo/node_modules/crypto-js/core.js:478
	                throw new Error('Malformed UTF-8 data');
	                ^

Error: Malformed UTF-8 data
    at Object.stringify (/Users/zhuge1/新/demo/node_modules/crypto-js/core.js:478:24)
    at WordArray.init.toString (/Users/zhuge1/新/demo/node_modules/crypto-js/core.js:215:38)
    at Object.<anonymous> (/Users/zhuge1/新/demo/test.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

```

**Comment by lkkmm** [comment]
i get same error, Have you solved it?

**Comment by suwu150** [comment]
i get same error, Have you solved it?
