### ISSUE TITLE
core.js:523 Uncaught Error: Malformed UTF-8 data

### ISSUE THREAD

**Issue by mdahsanekram** [brix/crypto-js#454]
I have written this function in javaScript to decrypt string in javaScript  and encript it in NodeJs and vise versa.

export const decrypt = (args) => {
  let plaintext = '';
  if (args) {
    const ciphertext = decodeURIComponent(args); // Remove decodeURIComponent if not URL-encoded
    const bytes = CryptoJS.AES.decrypt(ciphertext, process.env.REACT_APP_SECRETKEY);
    // Check if decryption was successful
    if (bytes.sigBytes > 0) {
      plaintext = bytes.toString(CryptoJS.enc.Utf8);
    } else {
      // Handle decryption failure, e.g., throw an error or return an appropriate value
      // console.error('Decryption failed');
    }
  }
  return plaintext;
};

and getting errors :
core.js:523 Uncaught Error: Malformed UTF-8 data
    at Object.stringify (core.js:523:1)
    at WordArray.init.toString (core.js:278:1)
    at decrypt (encodingdecoding.js:21:1)
    at NewLoyaltyCampaign (NewLoyaltyCampaign.js:152:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)

**Comment by mdahsanekram** [comment]
Encrypt ReactJs
export const encrypt = (args) => {
  try {
    if (args) {
      const ciphertext = CryptoJS.AES.encrypt(args, process.env.REACT_APP_SECRETKEY).toString();
      return encodeURIComponent(ciphertext);
    }
    return null;
  } catch (error) {
    // console.error('Encryption error:', error);
    return null;
  }
};

**Comment by mdahsanekram** [comment]
Node Js
const CryptoJS =require("crypto-js");

const encrypt=(args)=>{
   let ciphertext
    if(args){
         ciphertext = CryptoJS.AES.encrypt(args,process.env.SECRETKEY).toString();
    }
    return encodeURIComponent(ciphertext);
  }

  const decrypt=(args)=>{
    let plaintext='';
     if(args){
        const bytes = CryptoJS.AES.decrypt(decodeURIComponent(args),process.env.SECRETKEY);
         plaintext = bytes.toString(CryptoJS.enc.Utf8);
     }
     return plaintext;
   }
module.exports={encrypt,decrypt};

**Comment by vohoangankhanh** [comment]
this may help https://copyprogramming.com/howto/why-i-get-malformed-utf-8-data-error-on-crypto-js#google_vignette
