### ISSUE TITLE
Cannot read properties of undefined (reading 'AES') in typescript

### ISSUE THREAD

**Issue by 0-Sandy** [brix/crypto-js#489]
I am doing a project in nestjs using aes from crypto js but I get the error that aes doesn't exist in crypto js
`code`
```ts
import CryptoJS from 'crypto-js'

function encrypt(text: string, token: string): string {
  return CryptoJS.AES.encrypt(text, token).toString()
}

const encryptedAccessToken = encrypt(accessToken, process.env.TOKEN);
const encryptedRefreshToken = encrypt(refreshToken, process.env.TOKEN);
```
`console`
```pwsh
[Nest] 6352  - 05/07/2024, 6:50:18 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'AES')
TypeError: Cannot read properties of undefined (reading 'AES')
    at encrypt (E:\dor-nr\backend\src\auth\utils\DiscordStrategy.ts:9:19)
    at DiscordStrategy.validate (E:\dor-nr\backend\src\auth\utils\DiscordStrategy.ts:25:34)
    at DiscordStrategy.callback [as _verify] (E:\dor-nr\backend\node_modules\.pnpm\@nestjs+passport@10.0.3_@nestjs+common@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1__passport@0.7.0\node_modules\@nestjs\passport\dist\passport\passport.strategy.js:11:55)
    at E:\dor-nr\backend\node_modules\.pnpm\passport-oauth2@1.8.0\node_modules\passport-oauth2\lib\strategy.js:205:24
    at E:\dor-nr\backend\node_modules\.pnpm\passport-discord@0.1.4\node_modules\passport-discord\lib\strategy.js:99:24
    at E:\dor-nr\backend\node_modules\.pnpm\passport-discord@0.1.4\node_modules\passport-discord\lib\strategy.js:115:13
    at passBackControl (E:\dor-nr\backend\node_modules\.pnpm\oauth@0.10.0\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (E:\dor-nr\backend\node_modules\.pnpm\oauth@0.10.0\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
```

**Comment by 0-Sandy** [comment]
The error was that i had to use require
