### ISSUE TITLE
404 error installing crypto-js through bower

### ISSUE THREAD

**Issue by 5outh** [brix/crypto-js#63]
All of a sudden, I'm getting a 404 error when installing crypto-js through bower. This is happening both on my local machine (OSX) and inside a docker VM (debian stretch). I get the following trace when running `bower install crypto-js --verbose`:

```
$ bower install crypto-js --verbose

bower animate.scss#*        not-cached https://github.com/ianstormtaylor/animate.sass.git#*
bower animate.scss#*           resolve https://github.com/ianstormtaylor/animate.sass.git#*
bower api-console#~2.0.5        cached https://github.com/mulesoft/api-console.git#2.0.5
bower api-console#~2.0.5      validate 2.0.5 against https://github.com/mulesoft/api-console.git#~2.0.5
bower font-awesome#~4.2.0       cached https://github.com/FortAwesome/Font-Awesome.git#4.2.0
bower font-awesome#~4.2.0     validate 4.2.0 against https://github.com/FortAwesome/Font-Awesome.git#~4.2.0
bower skeuocard#~1.1.0          cached https://github.com/kenkeiter/skeuocard.git#1.1.0
bower skeuocard#~1.1.0        validate 1.1.0 against https://github.com/kenkeiter/skeuocard.git#~1.1.0
bower card#^1.3.2               cached https://github.com/jessepollak/card.git#1.3.2
bower card#^1.3.2             validate 1.3.2 against https://github.com/jessepollak/card.git#^1.3.2
bower Materialize#^0.97.7       cached https://github.com/Dogfalo/materialize.git#0.97.7
bower Materialize#^0.97.7     validate 0.97.7 against https://github.com/Dogfalo/materialize.git#^0.97.7
bower crypto-js#*               cached https://github.com/brix/crypto-js.git#3.1.6
bower crypto-js#*             validate 3.1.6 against https://github.com/brix/crypto-js.git#*
bower animate.scss#*          checkout master
bower crypto-js#*               cached https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip
bower crypto-js#*             validate https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
bower vkbeautify#ecfc3b9e2b911ad8ebd49600c4089aca30619f29           cached git://github.com/vkiryukhin/vkBeautify.git#ecfc3b9e2b
bower vkbeautify#ecfc3b9e2b911ad8ebd49600c4089aca30619f29         validate ecfc3b9e2b against git://github.com/vkiryukhin/vkBeautify.git#ecfc3b9e2b911ad8ebd49600c4089aca30619f29
bower raml-js-parser#e1513e34388d6bb6558f5cb5b221c19f90e225e5       cached git://github.com/raml-org/raml-js-parser.git#e1513e3438
bower raml-js-parser#e1513e34388d6bb6558f5cb5b221c19f90e225e5     validate e1513e3438 against git://github.com/raml-org/raml-js-parser.git#e1513e34388d6bb6558f5cb5b221c19f90e225e5
bower angular-highlightjs#~0.3.2                                    cached https://github.com/pc035860/angular-highlightjs.git#0.3.3
bower angular-highlightjs#~0.3.2                                  validate 0.3.3 against https://github.com/pc035860/angular-highlightjs.git#~0.3.2
bower angular-marked#0.0.18                                         cached https://github.com/Hypercubed/angular-marked.git#0.0.18
bower angular-marked#0.0.18                                       validate 0.0.18 against https://github.com/Hypercubed/angular-marked.git#0.0.18
bower angular-ui-codemirror#0.1.6                                   cached https://github.com/angular-ui/ui-codemirror.git#0.1.6
bower angular-ui-codemirror#0.1.6                                 validate 0.1.6 against https://github.com/angular-ui/ui-codemirror.git#0.1.6
bower angular#~1.3.17                                               cached https://github.com/angular/bower-angular.git#1.3.20
bower angular#~1.3.17                                             validate 1.3.20 against https://github.com/angular/bower-angular.git#~1.3.17
bower angular-sanitize#~1.3.17                                      cached https://github.com/angular/bower-angular-sanitize.git#1.3.20
bower angular-sanitize#~1.3.17                                    validate 1.3.20 against https://github.com/angular/bower-angular-sanitize.git#~1.3.17
bower codemirror#~3.15.0                                            cached https://github.com/marijnh/CodeMirror.git#3.15.0
bower codemirror#~3.15.0                                          validate 3.15.0 against https://github.com/marijnh/CodeMirror.git#~3.15.0
bower FileSaver#*                                                   cached https://github.com/eligrey/FileSaver.js.git#1.3.2
bower FileSaver#*                                                 validate 1.3.2 against https://github.com/eligrey/FileSaver.js.git#*
bower highlight-js#~7.0.1                                           cached https://github.com/isagalaev/highlight.js.git#7.0.1
bower highlight-js#~7.0.1                                         validate 7.0.1 against https://github.com/isagalaev/highlight.js.git#~7.0.1
bower marked#~0.3.1                                                 cached https://github.com/chjj/marked.git#0.3.6
bower marked#~0.3.1                                               validate 0.3.6 against https://github.com/chjj/marked.git#~0.3.1
bower slug#~0.8.0                                                   cached https://github.com/dodo/node-slug.git#0.8.0
bower slug#~0.8.0                                                 validate 0.8.0 against https://github.com/dodo/node-slug.git#~0.8.0
bower jquery#>=1.5                                                  cached https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery#>=1.5                                                validate 3.1.0 against https://github.com/jquery/jquery-dist.git#>=1.5
bower jquery#~2.1.1                                                 cached https://github.com/jquery/jquery-dist.git#2.1.4
bower jquery#~2.1.1                                               validate 2.1.4 against https://github.com/jquery/jquery-dist.git#~2.1.1
bower velocity#~1.1.0                                               cached https://github.com/julianshapiro/velocity.git#1.1.0
bower velocity#~1.1.0                                             validate 1.1.0 against https://github.com/julianshapiro/velocity.git#~1.1.0
bower jszip#~2.0.0                                                  cached https://github.com/Stuk/jszip.git#2.0.0
bower jszip#~2.0.0                                                validate 2.0.0 against https://github.com/Stuk/jszip.git#~2.0.0
bower raml-client-generator#~0.0.7                                  cached https://github.com/mulesoft/raml-client-generator.git#0.0.7
bower raml-client-generator#~0.0.7                                validate 0.0.7 against https://github.com/mulesoft/raml-client-generator.git#~0.0.7
bower crypto-js#*                                                      new version for https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
bower crypto-js#*                                                  resolve https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
bower crypto-js#*                                                 download https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip
bower animate.scss#*                                              resolved https://github.com/ianstormtaylor/animate.sass.git#62aebcf7c8
bower crypto-js#*                                                    EHTTP Status code of 404

Stack trace:
Error: Status code of 404
    at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)
    at Request.<anonymous> (/usr/local/lib/node_modules/bower/lib/util/download.js:91:36)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (/usr/local/lib/node_modules/bower/lib/node_modules/request/request.js:951:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
From previous event:
    at RetryOperation._fn (/usr/local/lib/node_modules/bower/lib/util/download.js:41:10)
    at RetryOperation.attempt (/usr/local/lib/node_modules/bower/lib/node_modules/retry/lib/retry_operation.js:56:8)
    at download (/usr/local/lib/node_modules/bower/lib/util/download.js:36:15)
    at UrlResolver._download (/usr/local/lib/node_modules/bower/lib/core/resolvers/UrlResolver.js:133:12)
    at UrlResolver._resolve (/usr/local/lib/node_modules/bower/lib/core/resolvers/UrlResolver.js:96:17)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.4.7
OS: Darwin 15.6.0 x64
```

**Comment by evanvosberg** [comment]
Seems like something strenge around here:

```
bower crypto-js#*               cached https://github.com/brix/crypto-js.git#3.1.6
bower crypto-js#*             validate 3.1.6 against https://github.com/brix/crypto-js.git#*
bower animate.scss#*          checkout master
bower crypto-js#*               cached https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip
bower crypto-js#*             validate https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
```

Different caches for the same package?

**Comment by 5outh** [comment]
@evanvosberg I meant to update this PR; I stopped depending on the package that was causing the issue, but it seems like an intermittent problem (none of my coworkers were able to reproduce it) so a caching issue seems like the likely culprit. I'll go ahead and close the issue!
