### ISSUE TITLE
npm remove crypto-js

### ISSUE THREAD

**Issue by abbgrade** [brix/crypto-js#79]
I installed the package using `npm install crypto-js` and to reinstall it with another parameter i wanted to uninstall it first. It failed with the message: "Tell the package author to fix their package.json file. JSON.parse"

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'remove',
1 verbose cli   'crypto-js' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly rollbackFailedOptional Starting
8 silly rollbackFailedOptional Finishing
9 silly runTopLevelLifecycles Finishing
10 silly install printInstalled
11 verbose stack Error: Failed to parse json
11 verbose stack Trailing comma in object at 36:3
11 verbose stack   },
11 verbose stack   ^
11 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
11 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
11 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
11 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
11 verbose stack     at tryToString (fs.js:455:3)
11 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
12 verbose cwd ABSOLUTEPATH
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "remove" "crypto-js"
15 error node v6.9.4
16 error npm  v3.10.10
17 error file ABSOLUTEPATH\package.json
18 error code EJSONPARSE
19 error Failed to parse json
19 error Trailing comma in object at 36:3
19 error   },
19 error   ^
20 error File: ABSOLUTEPATH\package.json
21 error Failed to parse package.json data.
21 error package.json must be actual JSON, not just JavaScript.
21 error
21 error This is not a bug in npm.
21 error Tell the package author to fix their package.json file. JSON.parse
22 verbose exit [ 1, true ]
```

As you might see i am using Windows 7 with npm 3.10.10 and node v6.9.4 .

Thanks
Steffen

**Comment by evanvosberg** [comment]
Don't know what went wrong there, but the package.json of CryptoJS does not have any version with a trailing comma at line 36.
