### ISSUE TITLE
Cannot read property 'hex' of undefined 

### ISSUE THREAD

**Issue by owlstack** [brix/crypto-js#84]
Hello, I'm using this library in my project and it compiles just fine. At runtime where I'm using the library, I get this error and the page I have cannot load: 
```

EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'Hex' of undefined
TypeError: Cannot read property 'Hex' of undefined
    at new CryptoService (http://localhost:4200/main.bundle.js:853:32)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:21:29)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:79210:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:79666:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:42811:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:59514:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:65359:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:24177:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:24144:26)
    at http://localhost:4200/vendor.bundle.js:24080:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:24080:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:24054:14)
    at http://localhost:4200/vendor.bundle.js:23622:22
    at SafeSubscriber._next (http://localhost:4200/vendor.bundle.js:4770:21)
```
I'm not sure how to proceed? 

I'm using angular-cli

**Comment by choucry13** [comment]
use @types/crypto-js to test if your problem resolve or not.

**Comment by txreplay** [comment]
I've got the same error, I can't use any CryptoJS function with Angular 5. 

As a workaround, this is working for me : 
```
declare var require: any;
let CryptoJS = require("crypto-js");
```

Instead of :

`import CryptoJS from 'crypto-js';`
