### ISSUE TITLE
Cannot read property 'sigBytes' of undefined

### ISSUE THREAD

**Issue by budingts** [brix/crypto-js#85]
Cannot read property 'sigBytes' of undefined

TypeError: Cannot read property 'sigBytes' of undefined
    at Object.init (/Volumes/T3/node_web/myapp/node_modules/crypto-js/hmac.js:53:21)
    at /Volumes/T3/node_web/myapp/node_modules/crypto-js/core.js:744:25
    at /Volumes/T3/node_web/myapp/routes/index.js:38:16
    at Layer.handle [as handle_request] (/Volumes/T3/node_web/myapp/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/T3/node_web/myapp/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Volumes/T3/node_web/myapp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Volumes/T3/node_web/myapp/node_modules/express/lib/router/layer.js:95:5)
    at /Volumes/T3/node_web/myapp/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Volumes/T3/node_web/myapp/node_modules/express/lib/router/index.js:330:12)
    at next (/Volumes/T3/node_web/myapp/node_modules/express/lib/router/index.js:271:10)

**Comment by FernandoZX** [comment]
i have the same error

**Comment by SPAHI4** [comment]
same for me

**Comment by ghost** [comment]
any luck with this ? i have the same behavior

**Comment by ghost** [comment]
same issue

**Comment by jackson-sandland** [comment]
same issue as well

**Comment by dmlzj** [comment]
me too

**Comment by dmlzj** [comment]
The parameter is wrong. It should be two, passed one

**Comment by alokshakya** [comment]
I also had the same error.
ERROR TypeError: Cannot read property 'sigBytes' of undefined
    at new init (crypto-js.js:1913)
    at Object.HmacSHA256 (crypto-js.js:744)
Later I put alert on parameters then found that one parameter is undefined. Please check parameters.

**Comment by sunWhereCode** [comment]
TypeError: Cannot read property 'sigBytes' of null

**Comment by prashanthbachu** [comment]
Same issue. It works in one environment and doesn't on other..any luck ?

**Comment by jayarjo** [comment]
My scripts worked on Windows, but now fail with the above mentioned errors in Ubuntu.

**Comment by vghetau** [comment]
took me a while to figure this out. HmacSHA256 is not receiving all parameters, or receives "undefined".

**Comment by a760109** [comment]
same issue, had any ideal to fix it ?

**Comment by jayzhou3** [comment]
I am getting this same issue and no one can fix the problem. 

```                    if (key.sigBytes > hasherBlockSizeBytes) {
                            ^

TypeError: Cannot read property 'sigBytes' of undefined
    at new init (/Users/jay/homework/cryptoTest/node_modules/crypto-js/hmac.js:53:22)
    at Object.HmacSHA256 (/Users/jay/homework/cryptoTest/node_modules/crypto-js/core.js:744:25)
    at Object.<anonymous> (/Users/jay/homework/cryptoTest/index.js:5:29)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
```

anyone has any idea how to fix it ??

**Comment by mwanchap** [comment]
I had the same issue - big thanks to @vghetau for pointing me in the right direction! This error means that one of the hmac crypto functions is receiving an undefined value in the "key" parameter (which is the second one). I found it by doing some logging to see which was undefined:

```javascript
console.log(signature); // prints the expected signature
console.log(secret); // prints "undefined"!
signature = CryptoJS.HmacSHA256(signature, secret);
```

From there it was straightforward to trace that variable back and see that it was being assigned incorrectly.  If you're getting this error from some other code that's ending up in a call to CryptoJS, you might have forgotten to assign some other variable it was passing in?

The line throwing the exception might be [this one](https://github.com/brix/crypto-js/blob/73c20dd8e0cb768af8a885d933d5c63e930ab3ac/src/hmac.js#L38), if you're curious. Although the line number doesn't match the one in @jayzhou3's answer...

**Comment by mwanchap** [comment]
Maybe if a guard clause was added to check for this and return a less cryptic error if the key is null?

**Comment by shide1989** [comment]
To me they should simply implement the latest version of CryptoJS

**Comment by saqibRafique** [comment]
> i have the same error

good reply

**Comment by Jeh212** [comment]
Does anyone have the solution already for this issue? Using the method PBKDF2 is getting the same problem returning as undefined!

**Comment by aldrichdev** [comment]
I had this same problem and it was because I forgot to select the Postman environment from the dropdown in the top right corner of the app. 🤦 [Reference](https://learning.postman.com/docs/sending-requests/managing-environments/#selecting-an-active-environment)

**Comment by arshadarshu028** [comment]
Please check is your signature is valid for CryptoJS , If in case  the signature is undefined then you will get the above error.

**Comment by naveensh26** [comment]
ERROR  TypeError: undefined is not an object (evaluating '_reactNativeCryptoJs.default.algo.HMAC.create')

Any help for HMAC REACT NATIVE

1) 
var hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, "Secret Passphrase");
hmac.update("Message Part 1");
hmac.update("Message Part 2");
hmac.update("Message Part 3");

var hash = hmac.finalize();

console.log("messaging part ----------" + hash);

2)

  // var hash = CryptoJS.HmacSHA256("Message", "Secret Passphrase");
  // console.log("hash---------- "+ hash)

ERROR  TypeError: undefined is not an object (evaluating '_reactNativeCryptoJs.default.algo.HMAC.create')
All are same error any help

**Comment by EscpLA** [comment]
> I also had the same error. ERROR TypeError: Cannot read property 'sigBytes' of undefined at new init (crypto-js.js:1913) at Object.HmacSHA256 (crypto-js.js:744) Later I put alert on parameters then found that one parameter is undefined. Please check parameters.

This is exactly my problem, thans a lot

**Comment by wangxiaoer5200** [comment]
CryptoJS.HmacSHA1:
maybe one of the parameters of the hash method before obtaining the signature is null

**Comment by aravind3566** [comment]
**On encryption.js** 

Just replace line from  **var hashKey = CryptoJS.PBKDF2**  to **var hashKey = CryptoJS.HmacSHA1**

**Comment by AlexC-ux** [comment]
same issue

const base64 = btoa(CryptoJS.HmacSHA1("/v1/request/callback/" + query  + CryptoJS.MD5(query)), secret);

**Comment by Rotem-55** [comment]
> took me a while to figure this out. HmacSHA256 is not receiving all parameters, or receives "undefined".

So how did you fix it? I'm afraid that's my problem either.

**Comment by matheussantiago-plana** [comment]
My error was happening on the following code

CryptoJS.HmacSHA256(rawSignature, secret);

my rawSignature was "undefined:123456" and my secret was "undefined", fixing these undefined fixed my problem.

**Comment by chiragtatva** [comment]
in my case CryptoJS.HmacSHA256(arg1, arg2) the value of arg1 or arg2 passed in the function was undefined
