### ISSUE TITLE
Cannot read property 'words' of undefined at crypto-js.js : 232

### ISSUE THREAD

**Issue by MingFrost** [brix/crypto-js#93]
I used HamSHA1 and alert the

**Comment by MingFrost** [comment]
incautiously click the submit.....
alert the 'Uncaught TypeError'....
How to slove this.....

**Comment by sahil290791** [comment]
@MingFrost Check if by mistake empty data is being passed for decryption.

**Comment by nolochemical** [comment]
crypto.AES.encrypt("cipher this stuff", **password_undefined** ) // You should define a password

TypeError: Cannot read property 'words' of undefined

crypto-js@3.1.8/aes.js:101
	            var keyWords = key.words;

**Comment by a4ankii** [comment]
i was also getting the this error using md5 and came up with following solution below:

 var pass=CryptoJS.MD5($('#login_password').val());
 var pass= pass+"";

**Comment by m-nathani** [comment]
Hi, did anyone found the solution to this ? 
Using: `    "crypto-js": "^3.1.9-1"` 
i am trying to make hash for  with following method:

`HmacSHA256(id + ":" + emai;, 'some-random-key');`

However getting an error on it as:
```
TypeError: Cannot read property 'words' of undefined
    at concat (core.js?21bf:232)
    at i (reamaze.js:3)
    at J (reamaze.js:1)
    at J (reamaze.js:1)
    at J (reamaze.js:1)
```

Can anyone please suggest a solution to it ?

**Comment by m-nathani** [comment]
Solution found:
Problem was JavaScript do not accepts bytes. So you need to convert this to a string format. Hex encoding is supported by CryptoJS as follows:

`CryptoJS.HmacSHA256("data", "some-random-shit").toString(CryptoJS.enc.Hex);
`

**Comment by git-marcopitra** [comment]
When we have this case above: 

```
const password = 'Mypassword123';
const encrypted = CryptoJS.AES.encrypt(password, 'my pass phrase');
```

And it throws you the error **Cannot read property 'words' of undefined**

You can solve this converting your string to a CryptoJS wordArray, generating the words that it's searching for.

```
const password = 'Mypassword123';
const encrypted =  CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(password), 'my pass phrase');
```

_I hope I helped_

**Comment by abdulmoizshaikh** [comment]
I was facing this issue when I go for production 
all was working fine on local enviornment 

eventually I got the solution
that was a silly mistake by the deployement team that

Solution:
they forget to pass the "secretKey" in .env file of deployed code
that's why we are facing the same issue 

I don't know what's the problem with your case 
But I have shared my solution 
that's why I shared may be it helped some one.

**Comment by paulohenrique001** [comment]
Utilize dessa forma que também dá certo

const secretKey = '123456789'; // or process.env.SECRET_KEY

const password = 'Mypassword123';
const encrypted =  CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(password), `${secretKey }`); // or ${process.env.SECRET_KEY}

**Comment by krishanyadav86** [comment]
i have same error 

TypeError: Cannot read properties of undefined (reading 'words')
    at Object._doReset (/app/node_modules/crypto-js/aes.js:103:33)
    at Object.reset (/app/node_modules/crypto-js/cipher-core.js:119:19)
    at Object.reset (/app/node_modules/crypto-js/cipher-core.js:461:27)
    at Object.init (/app/node_modules/crypto-js/cipher-core.js:104:19)

give a solution

**Comment by Masakona22** [comment]
I am getting an error with this code, what can I do?
Im parsing values that are coming in as user input.
var encrypted = undefined;
    console.log(encrypted);
    var iv = CryptoJS.lib.WordArray.random(16);
    encrypted = CryptoJS.AES.encrypt(this.EncryptionsForm.value.message, this.EncryptionsForm.value.key,{iv:iv});
    var encryptedMessage = encrypted.toString();

    console.log(encryptedMessage);

**Comment by ajiths10** [comment]
> I was facing this issue when I go for production all was working fine on local enviornment
> 
> eventually I got the solution that was a silly mistake by the deployement team that
> 
> Solution: they forget to pass the "secretKey" in .env file of deployed code that's why we are facing the same issue
> 
> I don't know what's the problem with your case But I have shared my solution that's why I shared may be it helped some one.

Thank you for posting this. I've been stuck with this issue for a while, and your help is greatly appreciated.

**Comment by balajigv67** [comment]
> Utilize dessa forma que também dá certo
> 
> const secretKey = '123456789'; // or process.env.SECRET_KEY
> 
> const password = 'Mypassword123'; const encrypted = CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(password), `${secretKey }`); // or ${process.env.SECRET_KEY}

In my case, ${process.env.SECRET_KEY} did not work, and I am getting an undefined output.

**Comment by bharat-mobiuso** [comment]
> > Utilize dessa forma que também dá certo
> > const secretKey = '123456789'; // or process.env.SECRET_KEY
> > const password = 'Mypassword123'; const encrypted = CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(password), `${secretKey }`); // or ${process.env.SECRET_KEY}
> 
> In my case, ${process.env.SECRET_KEY} did not work, and I am getting an undefined output.

Same issue faced by me, PLEASE CHECK YOUR ENV VARIABLE FIRST.

**Comment by sankalpmukim** [comment]
I am getting this issue inside of Next.js, in 2026 😭🫠

```
Error in GET /api/admin/is-admin proxy: TypeError: Cannot read properties of undefined (reading 'words')
    at Object._doReset (webpack-internal:///(rsc)/./node_modules/crypto-js/aes.js:96:33)
    at Object.reset (webpack-internal:///(rsc)/./node_modules/crypto-js/cipher-core.js:112:19)
    at Object.reset (webpack-internal:///(rsc)/./node_modules/crypto-js/cipher-core.js:454:27)
    at Object.init (webpack-internal:///(rsc)/./node_modules/crypto-js/cipher-core.js:97:19)
    at subtype.init (webpack-internal:///(rsc)/./node_modules/crypto-js/core.js:142:46)
    at subtype.init (webpack-internal:///(rsc)/./node_modules/crypto-js/core.js:142:46)
    at subtype.init (webpack-internal:///(rsc)/./node_modules/crypto-js/core.js:142:46)
    at Object.create (webpack-internal:///(rsc)/./node_modules/crypto-js/core.js:169:32)
    at Object.createEncryptor (webpack-internal:///(rsc)/./node_modules/crypto-js/cipher-core.js:56:26)
    at Object.encrypt (webpack-internal:///(rsc)/./node_modules/crypto-js/cipher-core.js:677:37)
    at Object.encrypt (webpack-internal:///(rsc)/./node_modules/crypto-js/cipher-core.js:194:59)
    at eval (webpack-internal:///(rsc)/./src/app/api/auth/axiosFetch.js:29:70)
    at async Axios.request (webpack-internal:///(rsc)/./node_modules/axios/lib/core/Axios.js:52:14)
    at async GET (webpack-internal:///(rsc)/./src/app/api/admin/is-admin/[email]/route.js:26:28)
    at async /Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57228
    at async eT.execute (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46851)
    at async eT.handle (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:58760)
    at async doRender (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:1366:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:1576:40)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:1496:28)
    at async DevServer.renderPageComponent (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:922:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/base-server.js:818:17)
    at async /Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/lib/router-server.js:179:21)
    at async handleRequest (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/lib/router-server.js:359:24)
    at async requestHandlerImpl (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/lib/router-server.js:383:13)
    at async Server.requestListener (/Users/sankalpmukim/code/copilot/cap/copilot-api-platform/node_modules/next/dist/server/lib/start-server.js:141:13)
```

It started coming randomly one day. Only happens on my laptop (Not on my teammate's laptops)
